[EDS-564] Adds vcard support to the cloud-native directory
UWIT-IAM/uw-husky-directory pull request #50
Opened 2021-04-05 20:08 UTC by tomthorogood

Closes EDS-564

See specific commits below for further details.

Broad strokes:

- Adds `/search/person/<token>/vcard` route, where the `/vcard` portion can later be expanded to return `/html` and `/json` results if needed (see also EDS-566).
- Adds "Download vcard" button to the full results template
- When a user clicks the "Download vcard" button, then the vcard is downloaded 🤔

The flask route invokes the `VCardService`, which fetches the person's data from PWS, then translates it into a `VCard` object which, when output as a dict to the jinja2 template engine, generates a vcard based on `vcard.vcf.jinja2`, using the `VCard` model exported dict as the template context.

If that sounded too complicated: It works just like HTML templates, but does for VCF instead.

2021-04-05 21:40 UTC, goulter reviewed
The vcards on this are the nearly the samesame in the old directory, cool! 
I downIoaded vcards for Cauce, and don't know if it makes a difference or not; there are a few fields where the data looks the same, just formatted different from what I can tell.
I bolded those fields.

_New Vcard:_
BEGIN:VCARD
**N:Cauce;Mari;
Ana**
FN:Ana Mari Cauce
TITLE:President
TITLE:Professor
TITLE:Professor
TITLE:Adjunct Professor
TITLE:Adjunct Professor
TITLE:President
**ORG:University of Washington
ORG:Psychology
ORG:American Ethnic Studies
ORG:College of Education
ORG:Gender, Women and Sexuality Studies
ORG:University of Washington**
EMAIL;type=WORK:president@uw.edu
TEL;type="voice":+1 206 543-5010
END:VCARD

_Old VCard_
BEGIN:VCARD
**N:Cauce;Ana Mari;;;**
FN:Ana Mari Cauce
TITLE:Adjunct Professor
TITLE:Adjunct Professor
TITLE:Professor
TITLE:Professor
TITLE:President
**ORG:University of Washington;Gender, Women and Sexuality Studies
ORG:University of Washington;College of Education
ORG:University of Washington;American Ethnic Studies
ORG:University of Washington;Psychology
ORG:University of Washington;University of Washington**
EMAIL;type=INTERNET;type=WORK:president@uw.edu
TEL;type=WORK:+1 206 543-5010
END:VCARD

2021-04-05 22:32 UTC, tomthorogood commented
Thanks, I double checked the old C code and found that [they hardcoded this value](https://github.com/UWIT-IAM/whitepages-ui/blob/master/vcui.c#L365) in there. I will follow suit; it makes sense if a person is merging a contact they have for someone with their UW contact info, the UW ORG field should include that information.

2021-04-05 22:35 UTC, tomthorogood commented
"N:Cauce;Mari;
Ana"

is a harder problem (Although, is the newline something you accidentally added in your comment, or was that verbatim from the vcard?) and I'll need to do a little bit of digging to see what fields the "names" should correlate to; this gets complicated because of preferred name vs. registered name, hopefully it won't be too bad...

2021-04-05 22:44 UTC, goulter commented
Well, at least one was straightforward :)
Hopefully the other isn't too much of a hole.

2021-04-05 22:44 UTC, tomthorogood commented
Also acknowledging the following difference: ` TEL;type=WORK:+1 206 543-5010` -- although the original is technically incorrect here; "Work" is not a valid value per [the specification. ](https://tools.ietf.org/html/rfc6350#section-6.4.1), and the original formatting does not use quotes.

2021-04-05 23:15 UTC, tomthorogood commented
@goulter am seeing the following output now after updates: Any other bits you can see?

```
BEGIN:VCARD
N:Cauce;Ana Mari
FN:Ana Mari Cauce
TITLE:President
TITLE:Professor
TITLE:Professor
TITLE:Adjunct Professor
TITLE:Adjunct Professor
TITLE:President
ORG:University of Washington;University of Washington
ORG:University of Washington;Psychology
ORG:University of Washington;American Ethnic Studies
ORG:University of Washington;College of Education
ORG:University of Washington;Gender, Women and Sexuality Studies
ORG:University of Washington;University of Washington
EMAIL;type=WORK:president@uw.edu
TEL;type="voice":+1 206 543-5010
END:VCARD
```

2021-04-06 16:41 UTC, goulter requested changes
I tested several names in the UW-IT dept and discovered more curiosities. 
There could be more, but I've tested about 10 names that I'm most familiar with. I'd imagine we'll very close to parity, not saying 100% as I don't know all combos :)

I didn't include fields that are already correct or where we already know there are corrections to made.

Cauce (also other names with similar data returned also have this):
TITLE fields: 1) President appears twice, 2) remaining fields appear in reverse order of old VCard
ORG fields: mimics TITLE fields 1) "ORG:University of Washington;University of Washington appears twice", 2) remaining fields appear in reverse order of old VCard
EMAIL field: old VCard includes "type=INTERNET;", new one does not.

NEW:
TITLE:President
TITLE:Professor
TITLE:Professor
TITLE:Adjunct Professor
TITLE:Adjunct Professor
TITLE:President
ORG:University of Washington
ORG:Psychology
ORG:American Ethnic Studies
ORG:College of Education
ORG:Gender, Women and Sexuality Studies
ORG:University of Washington
EMAIL;type=WORK:president@uw.edu

OLD:
TITLE:Adjunct Professor
TITLE:Adjunct Professor
TITLE:Professor
TITLE:Professor
TITLE:President
ORG:University of Washington;Gender, Women and Sexuality Studies
ORG:University of Washington;College of Education
ORG:University of Washington;American Ethnic Studies
ORG:University of Washington;Psychology
ORG:University of Washington;University of Washington
EMAIL;type=INTERNET;type=WORK:president@uw.edu

-----------------
Name search for Anne Tacazon:
TITLE field - new VCard adds ", Identity and Access Management"
ORG field - new VCard drops ";Identity and Access Management, "
NEW:
TITLE:Service Manager, Identity and Access Management
ORG:UW-IT: ITI: Workforce Strategy & Development
OLD:
TITLE:Service Manager
ORG:University of Washington;Identity and Access Management, UW-IT: ITI: Workforce Strategy & Development

---------------
Name search for Jim Tomlinson
TEL field - new VCard adds "text" in the "type" for cell.
NEW:
TEL;type="text,voice":+1 206 914-4069
OLD:
TEL;type=WORK:+1 206 914-4069
TEL;type=cell:+1 206 914-4069

--------------------------
Name search for Brad Greer:
Unknown field just after TEL - looks like a mailing address in the old VCard, we don't have this in the new VCard
item1.X-ABADR:us
item1.ADR;type=WORK:;Box 354842;4501 15th Ave NE Seattle, WA 98105-4527;;WA;

2021-04-06 16:58 UTC, tomthorogood commented
Thanks.

The `anne tacazon` case is out of our hands. PWS is a different data source, and classifies some fields differently. Our software is doing the right thing; the data is different.

re: `TEL`: Yes, the new output on phones is intended. This is actually within spec, the old vcard was not, see previous notes.

The mailing address has never been an explicit requirement of this product, and was not caught on any of the preceding reviews of the targeted fields by this product. If this is needed, that's a whole new feature I would rather defer to its own set of tasks, and I think should come _after_ launch, as it wasn't called out in the implementation plan reviewed by our leads and the marketing team. I will not address that here.

So, those oddities I think are out of scope here. I appreciate your thoroughness.

2021-04-06 17:02 UTC, goulter approved these changes
Then we are on good to go. Agreed on the mailing address no spec = no code :)

2021-04-06 17:25 UTC, tomthorogood commented
Oops, didn't run tests before updating this branch. Please hold.

2021-04-06 17:32 UTC, tomthorogood commented
Updated to fix the name parsing.

2021-04-06 18:52 UTC, goulter commented
Did we want to do anything with the repeated fields, like Cauce's _Title_ "President" or _ORG_  "University of Washington"?
https://github.com/UWIT-IAM/uw-husky-directory/pull/50#pullrequestreview-629190025

2021-04-06 18:57 UTC, tomthorogood commented
This is another issue where the software is correct, but the data is not: 

```
             {
                "EWPDept": "University of Washington",
                "EWPTitle": "President",
                "Primary": true
              },
              {
                "EWPDept": "Psychology",
                "EWPTitle": "Professor",
                "Primary": false
              },
              {
                "EWPDept": "American Ethnic Studies",
                "EWPTitle": "Professor",
                "Primary": false
              },
              {
                "EWPDept": "College of Education",
                "EWPTitle": "Adjunct Professor",
                "Primary": false
              },
              {
                "EWPDept": "Gender, Women and Sexuality Studies",
                "EWPTitle": "Adjunct Professor",
                "Primary": false
              },
              {
                "EWPDept": "University of Washington",
                "EWPTitle": "President",
                "Primary": false
              }
```

I think someone would have to request a new feature to deduplicate PWS "positions". I don't see any dedupe code in the original, whitepages-ui. I'm happy to add this as future work, but since it's a data quality issue, I'm not sure it needs to be fixed _here_.

2021-04-06 19:01 UTC, tomthorogood commented
(Conversely, this might be something that should e brought to the PWS team's attention. Perhaps it's a bug in _their_ code.)

2021-04-06 19:01 UTC, tomthorogood commented
(Conversely, this might be something that should e brought to the PWS team's attention. Perhaps it's a bug in _their_ code.)

2021-04-06 19:06 UTC, tomthorogood commented
As for repeated orgs, and the ordering of title/org, the code here is doing what the whitepages code was: going through every thing and plopping it in, regardless of repeats.

It seems that ORG could be unique, but i'm not sure if we explicitly want to always have a 1:1 title=>org relationship

2021-04-06 19:09 UTC, tomthorogood commented
So, TL;DR I think you raise good points but I am not sure whether those decisions are right, or just assumptions we're making, so we should hold off.

2021-04-06 19:15 UTC, tomthorogood commented
Created EDS-567 to capture these questions for follow-up

2021-04-06 19:58 UTC, goulter approved these changes
Thanks for looking at the data and software and explanations. I'll try to remember to bring EDS-567 to the Directory Services agenda.

2021-04-06 19:59 UTC, merged