[EDS-573] conditionally show box number
UWIT-IAM/uw-husky-directory pull request #57
Opened 2021-04-13 22:39 UTC by goulter

- Some folks won't have a box number, check for the data first, then show/not show.
- Closes  EDS-573

2021-04-13 23:10 UTC, tomthorogood requested changes
We have a test framework set up now, so I would ask that you please add a test for this and other changes going forward.

If you could please add an assertion to [test_render_full_success](http://github.com/UWIT-IAM/uw-husky-directory/blob/683d7045ae6809c5f4535f4f0ca8aab2762911f6/tests/blueprints/test_search_blueprint.py#L84-L84) to ensure the box number _is_ there when passed from the backend, that would be swell.

Likewise, I've gotten you started for the negative test case, if you could please extend it per the comments at the bottom, and add to the same class as above, I would appreciate it.

```python
   # This test works. I just ran it. 
    def test_render_full_no_box_number(self):
        self.mock_list_persons.return_value = [self.mock_people.published_student]
        self.flask_client.get('/saml/login', follow_redirects=True)
        with self.html_validator.validate_response(self.flask_client.post(
            '/search', data={'query': 'foo', 'length': 'full'}
        )) as html:
            assert not html.find_all('li', class_='dir-boxstuff')
            # also add an assertion that something else about the user /is/ there so that
            # we know the page rendered successfully with a null value
```

2021-04-14 01:32 UTC, goulter commented
Hmm, not sure why adding this line to the test above didn't work...
`assert html.find(string=re.compile("Last name is"))`

2021-04-14 01:33 UTC, goulter commented
Should I see a web driver report in the tests folder?

2021-04-14 19:11 UTC, goulter commented
I keep getting this error
FAILED ../tests/blueprints/test_search_blueprint.py::TestSearchBlueprint::test_render_full_no_box_number - AssertionError: Expected to find a <button> tag with text including 'download vcard' in <div class="usebar">

Code is in this [commit](https://github.com/UWIT-IAM/uw-husky-directory/pull/57/commits/194e1cb0f124e7d9141530bda927a772699fb68f#diff-dc9e99e3056e557f7096393d3cd6721845ca01d777fdd6175c8c8df8ee2687faR112)

2021-04-15 14:41 UTC, tomthorogood approved these changes

2021-04-15 14:46 UTC, merged